'use client'

import { jsPDF } from 'jspdf'
import html2canvas from 'html2canvas'

interface PdfPayload {
  globeElement?: HTMLElement | null
  trackedObjects: { name: string; alt: number; speed: number; type: string }[]
  kp: number | null
  solarWind: number | null
  passes: { sat: string; time: string; elevation: string }[]
  location: string
}

export async function exportMissionLog(payload: PdfPayload) {
  const pdf = new jsPDF('l', 'mm', 'a4')
  const w = 297, h = 210

  const page1 = () => {
    // Dark background
    pdf.setFillColor(8, 10, 22)
    pdf.rect(0, 0, w, h, 'F')

    // Header
    pdf.setFont('helvetica', 'bold')
    pdf.setTextColor(0, 212, 255)
    pdf.setFontSize(28)
    pdf.text('PROJECT ZENITH', w / 2, 28, { align: 'center' })

    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(10)
    pdf.setTextColor(136, 146, 164)
    pdf.text('MISSION LOG — ' + new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC', w / 2, 36, { align: 'center' })

    // Location
    pdf.setTextColor(0, 212, 255)
    pdf.setFontSize(11)
    pdf.text('Location: ' + payload.location, 20, 50)

    // Divider
    pdf.setDrawColor(0, 212, 255)
    pdf.setLineWidth(0.3)
    pdf.line(20, 56, w - 20, 56)

    // Tracked Objects
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(12)
    pdf.setTextColor(0, 255, 136)
    pdf.text('TRACKED OBJECTS', 20, 68)

    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(9)
    let y = 76
    for (const obj of payload.trackedObjects) {
      pdf.setTextColor(255, 255, 255)
      pdf.text(obj.name, 20, y)
      pdf.setTextColor(136, 146, 164)
      pdf.text(`ALT: ${obj.alt} km  SPD: ${obj.speed.toLocaleString('en-US')} km/h`, 90, y)
      y += 6
    }

    // Space Weather
    y = Math.max(y + 4, 130)
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(12)
    pdf.setTextColor(0, 212, 255)
    pdf.text('SPACE WEATHER', 20, y)
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(10)
    y += 8
    pdf.setTextColor(255, 255, 255)
    pdf.text(`KP Index: ${payload.kp !== null ? payload.kp.toFixed(2) : '—'}`, 20, y)
    pdf.text(`Solar Wind: ${payload.solarWind !== null ? Math.round(payload.solarWind).toLocaleString('en-US') + ' km/s' : '—'}`, 20, y + 7)

    // Passes
    y += 18
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(12)
    pdf.setTextColor(0, 212, 255)
    pdf.text('UPCOMING PASSES', 20, y)
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(10)
    y += 8
    for (const p of payload.passes) {
      pdf.setTextColor(255, 255, 255)
      pdf.text(`${p.sat} — ${p.time} — ${p.elevation}`, 20, y)
      y += 6
    }
  }

  page1()

  // Globe screenshot on page 2
  if (payload.globeElement) {
    pdf.addPage()
    pdf.setFillColor(8, 10, 22)
    pdf.rect(0, 0, w, h, 'F')
    try {
      const canvas = await html2canvas(payload.globeElement, {
        backgroundColor: '#080a16',
        scale: 0.8,
      })
      const imgData = canvas.toDataURL('image/png')
      pdf.addImage(imgData, 'PNG', 10, 10, w - 20, (w - 20) * (canvas.height / canvas.width))
    } catch { /* skip screenshot */ }
  }

  // Footer
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(8)
  pdf.setTextColor(42, 90, 42)
  pdf.text('Generated by Project Zenith · Mission Control System', w / 2, h - 8, { align: 'center' })

  pdf.save('zenith-mission-log.pdf')
}
